name: deepcoil
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel twine pytest pytest-cov
        pip install -r requirements.txt
    - name: Set environment
      run: |
        echo "::set-env name=PYTHONPATH::/home/runner/work/DeepCoil/DeepCoil"
    - name: Test with pytest
      run: |
        pytest -v
