name: deepcoil
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Fix wheel
      run: |
        pip install wheel==0.32.0
    - name: Install dependencies
      run: |
        pip install .
    - name: Set environment
      run: |
              echo "PYTHONPATH=/home/runner/work/DeepCoil/DeepCoil" >> $GITHUB_ENV
    - name: Test with pytest
      run: |
        pytest -v
